In [2]:
import pandas as pd

# path = "Top 100 Private Colleges.2003.csv"
colleges = pd.read_csv((r"D:\College_work\ML\LAB_5\Top100_PrivateColleges2003.csv"))

colleges_copy = colleges.copy()

colleges_copy.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21%,99/100%,3,71%,85%,10,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4
1,2,Rice University,TX,2787,24%,89/92%,5,68%,89%,19,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5
2,3,Williams College,MA,1985,23%,93/93%,8,89%,94%,1,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26
3,4,Swarthmore College,PA,1479,24%,94/98%,8,86%,92%,4,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21
4,5,Amherst College,MA,1618,18%,94/92%,9,84%,94%,5,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38

In [3]:
def clean_percentage(value):
    if pd.isnull(value):
        return value

    value = str(value).strip()

    if '%' in value:
        return value.replace('%','')

    if '/' in value:  # case like 99/100
        num, den = value.split('/')
        return (float(num)/float(den))*100

    return value

In [4]:
def clean_cost(value):
    if pd.isnull(value):
        return value

    value = str(value)
    value = value.replace('$','').replace(',','')

    return value

In [5]:
def clean_sat_act(value):
    if pd.isnull(value):
        return value

    value = str(value)

    parts = value.replace('/', ' ').split()

    numbers = []

    for p in parts:
        if p.isdigit():
            numbers.append(int(p))

    if numbers:
        return max(numbers)

    return None

In [6]:
for col in colleges_copy.columns:

    # Percentage columns
    if colleges_copy[col].astype(str).str.contains('%').any():
        colleges_copy[col] = colleges_copy[col].apply(clean_percentage)

    # Cost columns
    if colleges_copy[col].astype(str).str.contains('\$').any():
        colleges_copy[col] = colleges_copy[col].apply(clean_cost)

<>:8: SyntaxWarning: invalid escape sequence '\$'
<>:8: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Asus\AppData\Local\Temp\ipykernel_27700\3138372631.py:8: SyntaxWarning: invalid escape sequence '\$'
  if colleges_copy[col].astype(str).str.contains('\$').any():

In [7]:
colleges_copy['*SAT or ACT'] = colleges_copy['*SAT or ACT'].apply(clean_sat_act)

In [8]:
for col in colleges_copy.columns:
    colleges_copy[col] = pd.to_numeric(colleges_copy[col], errors='ignore')

C:\Users\Asus\AppData\Local\Temp\ipykernel_27700\2403232744.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  colleges_copy[col] = pd.to_numeric(colleges_copy[col], errors='ignore')

In [9]:
colleges_copy.info()

colleges_copy.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Overall Rank                   100 non-null    int64
 1   School                         100 non-null    object
 2   State                          100 non-null    object
 3   Undergrad. Enrollment          100 non-null    int64
 4   Admission Rate                 100 non-null    int64
 5   *SAT or ACT                    99 non-null     float64
 6   Student/faculty Ratio          100 non-null    int64
 7   4-year Grad. Rate              100 non-null    int64
 8   6-year Grad. Rate              100 non-null    int64
 9   Quality Rank                   100 non-null    int64
 10  Total Costs                    100 non-null    int64
 11  Cost After Need-based Aid      100 non-null    int64
 12  Need Met                       100 non-null    object
 13  Aid From Grants                100 non-null    int64
 14  Cost After Non-Need-Based Aid  100 non-null    int64
 15  Non-Need-Based Aid+            73 non-null     float64
 16  Average Debt                   100 non-null    int64
 17  Cost Rank                      100 non-null    int64
dtypes: float64(2), int64(13), object(3)
memory usage: 14.2+ KB

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21,100.0,3,71,85,10,32682,10981,100,93,18553,15.0,10244,4
1,2,Rice University,TX,2787,24,92.0,5,68,89,19,28350,14779,100,88,22418,34.0,12705,5
2,3,Williams College,MA,1985,23,93.0,8,89,94,1,36550,14737,100,89,33251,NaN,12316,26
3,4,Swarthmore College,PA,1479,24,98.0,8,86,92,4,38676,17386,100,85,11404,2.0,12759,21
4,5,Amherst College,MA,1618,18,94.0,9,84,94,5,38492,14453,100,92,33411,NaN,11544,38